# Generated by Django 4.2.3 on 2023-07-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-date_created',)},
        ),
    ]
